apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pi-hole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      containers:
        - image: pihole/pihole:2023.03.1
          imagePullPolicy: IfNotPresent
          name: pihole
          env:
            - name: TZ
              value: "Australia/Brisbane"
            - name: DNSMASQ_USER
              value: "root"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_RAW
                - NET_ADMIN
                - SYS_NICE
                - CHOWN
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          volumeMounts:
            - name: etc
              mountPath: '/etc/pihole'
            - name: dnsmasq
              mountPath: '/etc/dnsmasq.d'
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
      restartPolicy: Always
      volumes:
        - name: etc
          hostPath:
            path: /opt/volumes/pi-hole/etc
        - name: dnsmasq
          hostPath:
            path: /opt/volumes/pi-hole/dnsmasq.d
